var Temas = {
  roxoEscuro: {
    "--cor-fundo": "#28243c",
    "--cor-principal-1": "#7949dd",
    "--cor-principal-2": "#b19ae4",
    "--cor-principal-3": "#8f06ff67",
    "--cor-texto": "white",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(13%) sepia(25%) saturate(864%) hue-rotate(210deg) brightness(96%) contrast(96%)",
  },
  roxoClaro: {
    "--cor-fundo": "#ececec",
    "--cor-principal-1": "#7949dd",
    "--cor-principal-2": "#b19ae4",
    "--cor-principal-3": "#8f06ff67",
    "--cor-texto": "black",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(92%) sepia(56%) saturate(12%) hue-rotate(220deg) brightness(118%) contrast(85%)",
  },
  amareloEscuro: {
    "--cor-fundo": "#0d1017",
    "--cor-principal-1": "#d4993a",
    "--cor-principal-2": "#d4b684",
    "--cor-principal-3": "#49424e67",
    "--cor-texto": "white",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(4%) sepia(6%) saturate(4849%) hue-rotate(184deg) brightness(96%) contrast(94%)",
  },
  amareloClaro: {
    "--cor-fundo": "#ececec",
    "--cor-principal-1": "#d4993a",
    "--cor-principal-2": "#d4b684",
    "--cor-principal-3": "#49424e67",
    "--cor-texto": "black",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(92%) sepia(56%) saturate(12%) hue-rotate(220deg) brightness(118%) contrast(85%)",
  },
  vermelhoEscuro: {
    "--cor-fundo": "#130d17",
    "--cor-principal-1": "#990011FF",
    "--cor-principal-2": "#D54754",
    "--cor-principal-3": "#FF809B",
    "--cor-texto": "white",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(4%) sepia(4%) saturate(7275%) hue-rotate(232deg) brightness(95%) contrast(95%)",
  },
  vermelhoClaro: {
    "--cor-fundo": "#ececec",
    "--cor-principal-1": "#990011FF",
    "--cor-principal-2": "#D54754",
    "--cor-principal-3": "#FF809B",
    "--cor-texto": "black",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(92%) sepia(56%) saturate(12%) hue-rotate(220deg) brightness(118%) contrast(85%)",
  },
  rosaEscuro: {
    "--cor-fundo": "#B7819B",
    "--cor-principal-1": "#FF8DC7",
    "--cor-principal-2": "#FFACC7",
    "--cor-principal-3": "#FFDDD2",
    "--cor-texto": "white",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(62%) sepia(8%) saturate(1417%) hue-rotate(279deg) brightness(90%) contrast(80%)",
  },
  rosaClaro: {
    "--cor-fundo": "#ececec",
    "--cor-principal-1": "#FF8DC7",
    "--cor-principal-2": "#FFACC7",
    "--cor-principal-3": "#FFDDD2",
    "--cor-texto": "black",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(92%) sepia(56%) saturate(12%) hue-rotate(220deg) brightness(118%) contrast(85%)",
  },
  azulEscuro: {
    "--cor-fundo": "#404756",
    "--cor-principal-1": "#8AAAE5",
    "--cor-principal-2": "#b2c7ec",
    "--cor-principal-3": "#cbd6e7",
    "--cor-texto": "white",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(25%) sepia(4%) saturate(2396%) hue-rotate(183deg) brightness(99%) contrast(88%)",
  },
  azulClaro: {
    "--cor-fundo": "#ececec",
    "--cor-principal-1": "#8AAAE5",
    "--cor-principal-2": "#b2c7ec",
    "--cor-principal-3": "#cbd6e7",
    "--cor-texto": "black",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(92%) sepia(56%) saturate(12%) hue-rotate(220deg) brightness(118%) contrast(85%)",
  },
  verdeEscuro: {
    "--cor-fundo": "#3B4A3F",
    "--cor-principal-1": "#2BAE66FF",
    "--cor-principal-2": "#8bdbaf",
    "--cor-principal-3": "#aee2c6",
    "--cor-texto": "white",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(26%) sepia(12%) saturate(610%) hue-rotate(83deg) brightness(97%) contrast(92%)",
  },
  verdeClaro: {
    "--cor-fundo": "#ececec",
    "--cor-principal-1": "#2BAE66FF",
    "--cor-principal-2": "#8bdbaf",
    "--cor-principal-3": "#aee2c6",
    "--cor-texto": "black",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(92%) sepia(56%) saturate(12%) hue-rotate(220deg) brightness(118%) contrast(85%)",
  },
  retroEscuro: {
    "--cor-fundo": "#6F5643",
    "--cor-principal-1": "#cc6b49",
    "--cor-principal-2": "#d2a24c",
    "--cor-principal-3": "#73bda8",
    "--cor-texto": "white",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(32%) sepia(38%) saturate(378%) hue-rotate(343deg) brightness(97%) contrast(89%)",
  },
  retroClaro: {
    "--cor-fundo": "#ece6c2",
    "--cor-principal-1": "#cc6b49",
    "--cor-principal-2": "#d2a24c",
    "--cor-principal-3": "#73bda8",
    "--cor-texto": "black",
    "--cor-texto-botoes": "white",
    "--cor-texto-container": "black",
    "--cor-container": "white",
    "--cor-filtro":
      "invert(94%) sepia(9%) saturate(605%) hue-rotate(8deg) brightness(97%) contrast(95%)",
  },
}